bcmdhd: fix void argument for -Wstrict-prototypes
Fixes several build errors similar to the following:

  wl_cfg_btcoex.c:439:37: error: a function declaration without a \
      prototype is deprecated in all versions of C \
      [-Werror,-Wstrict-prototypes]
  void wl_cfg80211_btcoex_kill_handler()
                                      ^
                                      void

Bug: 255532233
Change-Id: Iee06b05209ca128a31e51510a97722dc06942c6c
Signed-off-by: Carlos Llamas <cmllamas@google.com>